'use client';

import { useEffect, useState, Suspense } from 'react';
import { supabase } from '@/lib/supabase';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import PaymentModal from '../components/PaymentModal';

function DashboardContent() {
    const [user, setUser] = useState(null);
    const [profile, setProfile] = useState(null);
    const [books, setBooks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [modalOpen, setModalOpen] = useState(false);
    const [welcomeModalOpen, setWelcomeModalOpen] = useState(false);
    const [selectedBookId, setSelectedBookId] = useState(null);

    const router = useRouter();
    const searchParams = useSearchParams();

    useEffect(() => {
        async function fetchDashboardData() {
            try {
                // 1. Get User
                const { data: { session }, error } = await supabase.auth.getSession();
                if (error || !session) {
                    router.push('/login');
                    return;
                }
                setUser(session.user);

                // 2. Get Profile (with Subscription Status)
                const { data: profileData } = await supabase
                    .from('profiles')
                    .select('*')
                    .eq('id', session.user.id)
                    .single();
                setProfile(profileData);

                // 3. Get Books (Generated by User)
                const { data: booksData } = await supabase
                    .from('generated_books')
                    .select('*')
                    .eq('user_id', session.user.id)
                    .order('created_at', { ascending: false });

                setBooks(booksData || []);

            } catch (err) {
                console.error(err);
                // router.push('/login');
            } finally {
                setLoading(false);
            }
        }
        fetchDashboardData();
    }, [router]);

    useEffect(() => {
        const action = searchParams.get('action');
        const unlockBookId = searchParams.get('unlock_book');

        if (action === 'club_welcome' && unlockBookId) {
            setSelectedBookId(unlockBookId);
            setWelcomeModalOpen(true);
            // Clean URL? Optional but good UX.
        }
    }, [searchParams]);

    // Access Logic Checker
    const canAccessBook = (book) => {
        // 1. Club Member?
        if (profile?.subscription_status === 'active') return true;
        // 2. Book Unlocked (One-off purchase)?
        if (book.is_unlocked) return true;

        return false;
    };

    const handleAction = (book, action) => {
        if (canAccessBook(book)) {
            // Authorized
            if (action === 'read') router.push(`/read/${book.id}`);
            if (action === 'download') window.open(`/api/download/${book.id}`, '_blank');
        } else {
            // Unauthorized -> Show Payment Modal
            setSelectedBookId(book.id);
            setModalOpen(true);
        }
    };

    if (loading) return <div className="min-h-screen bg-gray-50 pt-32 flex justify-center"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div></div>;

    return (
        <div className="min-h-screen bg-[#FDFBF7] pt-32 pb-20 relative">
            {/* Background Pattern */}
            <div className="absolute inset-0 z-0 opacity-40 pointer-events-none" style={{ backgroundImage: 'url(/images/pattern_bg.png)', backgroundSize: '400px' }}></div>

            <div className="container mx-auto px-4 relative z-10">

                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-center mb-12 gap-6">
                    <div>
                        <h1 className="text-3xl font-black text-gray-900">Mon Espace Parents</h1>
                        <p className="text-gray-600 font-medium pt-1">Bienvenue, {profile?.full_name || user?.email}</p>
                        {profile?.subscription_status === 'active' && (
                            <span className="inline-block mt-2 px-3 py-1 bg-gradient-to-r from-orange-400 to-pink-500 text-white rounded-full text-xs font-bold uppercase tracking-wider shadow-md">
                                Membre Club VIP 🌟
                            </span>
                        )}
                    </div>
                    <Link href="/books" className="bg-white text-orange-600 px-6 py-3 rounded-xl font-bold border-2 border-orange-100 hover:border-orange-500 hover:bg-orange-50 transition-all shadow-sm">
                        + Nouvelle Histoire
                    </Link>
                </div>

                {/* Content */}
                {books.length === 0 ? (
                    <div className="bg-white/80 backdrop-blur-sm rounded-[2.5rem] shadow-xl border border-white/50 p-12 text-center max-w-4xl mx-auto mt-10">
                        <div className="mb-6 flex justify-center">
                            {/* Magic Book GIF */}
                            <img
                                src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3Z5eXAzZ3Z5eXAzZ3Z5eXAzZ3Z5eXAzZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKSjRrfIPjeiVyM/giphy.gif"
                                alt="Magic Book"
                                className="w-48 h-auto rounded-2xl mix-blend-multiply"
                            />
                        </div>
                        <h2 className="text-3xl md:text-4xl font-black text-gray-900 mb-4">L'aventure commence ici !</h2>
                        <p className="text-gray-500 max-w-lg mx-auto mb-10 text-lg leading-relaxed">
                            Votre enfant n'a pas encore son histoire magique.<br />
                            Créez une histoire unique en quelques secondes et voyez ses yeux s'illuminer.
                        </p>
                        <Link href="/books" className="inline-block bg-orange-600 text-white px-10 py-5 rounded-full font-bold text-xl hover:bg-orange-700 transition-all shadow-xl hover:shadow-orange-600/30 transform hover:-translate-y-1">
                            Créer sa première histoire ✨
                        </Link>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {books.map((book) => (
                            <div key={book.id} className="bg-white rounded-3xl shadow-md border border-gray-100 overflow-hidden hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1 group">
                                {/* Cover Helper */}
                                <div className="aspect-[4/5] bg-orange-50 relative overflow-hidden">
                                    {book.cover_url ? (
                                        <Image src={book.cover_url} alt={book.title} fill className="object-cover transition-transform duration-700 group-hover:scale-105" />
                                    ) : (
                                        <div className="absolute inset-0 flex items-center justify-center text-orange-200">
                                            <span className="text-6xl group-hover:scale-110 transition-transform">📖</span>
                                        </div>
                                    )}

                                    {/* Lock Overlay if Locked */}
                                    {!canAccessBook(book) && (
                                        <div className="absolute inset-0 bg-black/60 backdrop-blur-[2px] flex flex-col items-center justify-center text-white p-6 text-center">
                                            <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md mb-4 shadow-lg">
                                                <span className="text-2xl">🔒</span>
                                            </div>
                                            <span className="font-bold text-lg mb-1">Histoire terminée</span>
                                            <span className="text-sm opacity-80">Débloquez pour lire</span>
                                        </div>
                                    )}
                                </div>

                                <div className="p-6">
                                    <h3 className="font-bold text-xl text-gray-900 mb-2 line-clamp-2 leading-tight">
                                        {book.child_name ? `${book.child_name} et ` : ''}{book.title_template || book.title || 'l\'Aventure Magique'}
                                    </h3>
                                    <p className="text-gray-400 text-xs font-bold uppercase tracking-wider mb-6">
                                        {new Date(book.created_at).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })}
                                    </p>

                                    <div className="flex gap-3">
                                        <button
                                            onClick={() => handleAction(book, 'read')}
                                            className={`flex-1 py-3 px-4 rounded-xl font-bold border-2 transition-colors flex items-center justify-center gap-2 ${canAccessBook(book)
                                                ? 'border-orange-500 bg-orange-500 text-white hover:bg-orange-600 hover:border-orange-600 shadow-lg hover:shadow-orange-500/30'
                                                : 'border-orange-200 text-orange-500 hover:bg-orange-50'
                                                }`}
                                        >
                                            {canAccessBook(book) ? 'Lire 📖' : 'Débloquer 🔓'}
                                        </button>

                                        {canAccessBook(book) && (
                                            <button
                                                onClick={() => handleAction(book, 'download')}
                                                className="w-12 h-12 flex items-center justify-center rounded-xl font-bold border-2 border-orange-100 text-orange-400 hover:text-orange-600 hover:border-orange-300 hover:bg-orange-50 transition-colors"
                                                title="Télécharger PDF"
                                            >
                                                📥
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Smart Paywall Modal */}
            <PaymentModal
                isOpen={modalOpen}
                onClose={() => setModalOpen(false)}
                user={user}
                bookId={selectedBookId}
            />

            {/* WELCOME CLUB MODAL */}
            {welcomeModalOpen && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/80 backdrop-blur-sm"></div>
                    <div className="relative bg-white rounded-3xl p-8 max-w-lg w-full text-center shadow-2xl animate-in zoom-in-95 border-4 border-orange-200">
                        <div className="text-6xl mb-4 animate-bounce">🎉</div>
                        <h2 className="text-3xl font-black text-gray-900 mb-2">Bienvenue au Club ! 🌟</h2>
                        <p className="text-gray-600 mb-8 text-lg">
                            Votre abonnement est actif et vous brillez déjà !<br />
                            Vous avez <strong className="text-orange-600">1 crédit disponible</strong>.
                        </p>

                        <div className="bg-orange-50 p-6 rounded-2xl mb-8 border border-orange-100">
                            <p className="font-bold text-gray-800 mb-2">Voulez-vous débloquer votre livre maintenant ?</p>
                            <p className="text-sm text-gray-500">Cela utilisera 1 crédit pour générer le reste de l'histoire.</p>
                        </div>

                        <button
                            onClick={async () => {
                                try {
                                    const res = await fetch('/api/books/unlock', {
                                        method: 'POST',
                                        headers: { 'Content-Type': 'application/json' },
                                        body: JSON.stringify({ bookId: selectedBookId })
                                    });
                                    if (res.ok) {
                                        // TRIGGER WORKER (Fire and Forget)
                                        fetch('/api/books/process-purchased', {
                                            method: 'POST',
                                            headers: { 'Content-Type': 'application/json' },
                                            body: JSON.stringify({ bookId: selectedBookId })
                                        }).catch(err => console.error("Worker Trigger Error", err));

                                        // Redirect to Reader
                                        router.push(`/read/${selectedBookId}`);
                                    } else {
                                        alert("Erreur lors du déblocage.");
                                    }
                                } catch (e) { console.error(e); }
                            }}
                            className="w-full bg-green-500 text-white py-4 rounded-xl font-bold text-xl hover:bg-green-600 transition-all shadow-lg hover:shadow-green-500/30 flex items-center justify-center gap-2"
                        >
                            <span>🔓</span> Oui, débloquer (Utiliser 1 crédit)
                        </button>
                        <button
                            onClick={() => setWelcomeModalOpen(false)}
                            className="mt-4 text-gray-400 text-sm hover:text-gray-600"
                        >
                            Non, plus tard
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}

export default function Dashboard() {
    return (
        <Suspense fallback={<div className="min-h-screen pt-32 text-center">Chargement...</div>}>
            <DashboardContent />
        </Suspense>
    );
}
