'use client';

import { useEffect, useState, Suspense } from 'react';
import { supabase } from '@/lib/supabase';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import PaymentModal from '../components/PaymentModal';
import ClubModal from '../components/ClubModal';
import DashboardBottomNav from '../components/DashboardBottomNav';

function DashboardContent() {
    const [user, setUser] = useState(null);
    const [profile, setProfile] = useState(null);
    const [books, setBooks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [modalOpen, setModalOpen] = useState(false);
    const [welcomeModalOpen, setWelcomeModalOpen] = useState(false);
    const [selectedBookId, setSelectedBookId] = useState(null);
    const [childName, setChildName] = useState('Votre enfant');

    const [creditModalOpen, setCreditModalOpen] = useState(false);
    const [clubModalOpen, setClubModalOpen] = useState(false);

    const router = useRouter();
    const searchParams = useSearchParams();

    useEffect(() => {
        async function fetchDashboardData() {
            try {
                // 1. Get User
                const { data: { session }, error } = await supabase.auth.getSession();
                if (error || !session) {
                    router.push('/login');
                    return;
                }
                setUser(session.user);

                // 2. Get Profile (with Subscription Status)
                const { data: profileData } = await supabase
                    .from('profiles')
                    .select('*')
                    .eq('id', session.user.id)
                    .single();
                setProfile(profileData);

                // 2.1 Get Children
                const { data: childrenData } = await supabase
                    .from('children')
                    .select('*')
                    .eq('user_id', session.user.id)
                    .limit(1);

                if (childrenData && childrenData.length > 0) {
                    setChildName(childrenData[0].first_name);
                }

                // 3. Get Books (Generated by User)
                const { data: booksData } = await supabase
                    .from('generated_books')
                    .select('*')
                    .eq('user_id', session.user.id)
                    .order('created_at', { ascending: false });

                setBooks(booksData || []);

            } catch (err) {
                console.error(err);
                // router.push('/login');
            } finally {
                setLoading(false);
            }
        }
        fetchDashboardData();
    }, [router]);

    useEffect(() => {
        const action = searchParams.get('action');
        const unlockBookId = searchParams.get('unlock_book');

        if (action === 'club_welcome' && unlockBookId) {
            setSelectedBookId(unlockBookId);
            setWelcomeModalOpen(true);
        } else if (action === 'subscribe') {
            setModalOpen(true);
        }
    }, [searchParams]);

    // Access Logic
    const canAccessBook = (book) => {
        // 1. If unlocked (Paid or Credit), always yes
        if (book.is_unlocked) return true;
        // 2. If Club Member AND Author, yes (Streaming Rights)
        if (profile?.subscription_status === 'active' && book.user_id === user?.id) return true;
        return false;
    };

    const canDownloadBook = (book) => {
        // Only if fully unlocked PDF
        return book.pdf_unlocked === true;
    };

    const downloadBook = async (bookId) => {
        try {
            // Get or create download token
            // If locked and user has credits, this endpoint will AUTO-DEDUCT (so only call if confirmed or already unlocked)
            const response = await fetch(`/api/download-secure/${bookId}/get-token`, {
                method: 'POST'
            });

            if (response.status === 402) {
                // Payment Required (Should be caught by UI logic before, but failsafe)
                alert("Crédits insuffisants.");
                return;
            }

            if (!response.ok) {
                alert('Erreur lors de la génération du lien.');
                return;
            }

            const { token } = await response.json();

            // If successful, optimistically update UI
            setBooks(books.map(b => b.id === bookId ? { ...b, pdf_unlocked: true } : b));
            // Also decrement credits locally if we just used one? (Complex to know if we used one or if it was already unlocked)
            // But get-token logic is idempotent if already unlocked.
            // Ideally we should reload profile or track it.

            window.open(`/api/download-secure/${bookId}?token=${token}`, '_blank');
        } catch (error) {
            console.error('Download error:', error);
            alert('Erreur lors du téléchargement');
        }
    };

    const handleAction = (book, action) => {
        if (action === 'read') {
            if (canAccessBook(book)) {
                router.push(`/read/${book.id}`);
            } else {
                setSelectedBookId(book.id);
                setModalOpen(true);
            }
        } else if (action === 'download') {
            if (canDownloadBook(book)) {
                // Already owned/unlocked PDF -> Download directly
                downloadBook(book.id);
            } else {
                // Locked PDF. Check credits.
                setSelectedBookId(book.id);
                if ((profile?.monthly_credits || 0) > 0) {
                    // Has credits -> Confirm Use
                    setCreditModalOpen(true);
                } else {
                    // No credits -> Pay
                    setModalOpen(true);
                }
            }
        }
    };

    if (loading) return <div className="min-h-screen bg-gray-50 pt-32 flex justify-center"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div></div>;

    // Gamification Logic - Dynamic Badges
    const totalBooks = books.length;
    const badges = [
        { id: 'first_book', name: 'Explorateur', icon: '🌍', threshold: 1, unlocked: totalBooks >= 1, description: 'Créer sa 1ère histoire' },
        { id: 'three_books', name: 'Aventurier', icon: '⛺', threshold: 3, unlocked: totalBooks >= 3, description: 'Créer 3 histoires' },
        { id: 'five_books', name: 'Rat de Bibliothèque', icon: '📚', threshold: 5, unlocked: totalBooks >= 5, description: 'Créer 5 histoires' },
        { id: 'ten_books', name: 'Maître des Mondes', icon: '🧙‍♂️', threshold: 10, unlocked: totalBooks >= 10, description: 'Créer 10 histoires' },
    ];
    const unlockedBadges = badges.filter(b => b.unlocked);

    // Progress to next badge
    const nextBadge = badges.find(b => !b.unlocked);
    const progressPercent = nextBadge
        ? Math.min(100, Math.round((totalBooks / nextBadge.threshold) * 100))
        : 100;

    return (
        <div className="min-h-screen bg-[#FDFBF7] pt-32 pb-20 relative">
            {/* Background Pattern */}
            <div className="absolute inset-0 z-0 opacity-40 pointer-events-none" style={{ backgroundImage: 'url(/images/pattern_bg.png)', backgroundSize: '400px' }}></div>

            <div className="container mx-auto px-4 relative z-10">

                {/* Title & Context */}
                {books.length > 0 && (
                    <div className="mb-8 mt-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                        <h1 className="text-3xl font-black text-gray-900 border-l-8 border-orange-500 pl-4 py-1">
                            La Bibliothèque de {profile?.full_name?.split(' ')[0] || user?.email?.split('@')[0]}
                        </h1>
                        {profile?.subscription_status === 'active' && (
                            <div className="flex items-center gap-2 bg-gradient-to-r from-orange-500 to-orange-600 text-white px-6 py-3 rounded-full shadow-lg">
                                <span className="text-2xl">🏆</span>
                                <div className="flex flex-col">
                                    <span className="font-bold text-sm">Membre du Club</span>
                                    <span className="text-xs opacity-90">{profile?.monthly_credits || 0} crédit{(profile?.monthly_credits || 0) > 1 ? 's' : ''} restant{(profile?.monthly_credits || 0) > 1 ? 's' : ''}</span>
                                </div>
                            </div>
                        )}
                    </div>
                )}

                {/* PASSPORT WIDGET (Gamification) */}
                {books.length > 0 && (
                    <div className="mb-10 bg-white rounded-[2rem] p-6 md:p-8 shadow-xl border border-gray-100 relative overflow-hidden flex flex-col md:flex-row gap-8 items-center justify-between">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-orange-100 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>

                        <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                                <span className="text-3xl">🎫</span>
                                <h2 className="text-2xl font-black font-chewy text-gray-800">Passeport de Lecture</h2>
                            </div>
                            <p className="text-gray-500 text-sm mb-4">
                                {childName} a découvert <strong>{totalBooks} livre{totalBooks > 1 ? 's' : ''}</strong> !
                                {nextBadge ? ` Encore ${nextBadge.threshold - totalBooks} pour devenir ${nextBadge.name}.` : ' Niveau maximum atteint !'}
                            </p>

                            {/* Progress Bar */}
                            <div className="w-full bg-orange-50 rounded-full h-3 mb-2 relative overflow-hidden">
                                <div
                                    className="bg-gradient-to-r from-orange-400 to-orange-500 h-3 rounded-full transition-all duration-1000 ease-out"
                                    style={{ width: `${progressPercent}%` }}
                                ></div>
                            </div>
                        </div>

                        {/* Badges Container */}
                        <div className="flex gap-4 md:gap-6 flex-wrap justify-center bg-gray-50/50 p-4 rounded-3xl border border-gray-100">
                            {badges.map((badge) => (
                                <div key={badge.id} className="flex flex-col items-center group relative cursor-help">
                                    <div className={`w-14 h-14 md:w-16 md:h-16 rounded-full flex items-center justify-center text-3xl shadow-sm transition-all duration-300 ${badge.unlocked ? 'bg-orange-100 border-2 border-orange-400 transform hover:scale-110 hover:rotate-12 hover:shadow-orange-200 shadow-md' : 'bg-gray-100 grayscale opacity-40'}`}>
                                        {badge.icon}
                                    </div>
                                    <span className={`text-[10px] md:text-xs font-bold mt-2 text-center max-w-[64px] leading-tight ${badge.unlocked ? 'text-orange-700' : 'text-gray-400'}`}>
                                        {badge.name}
                                    </span>

                                    {/* Tooltip */}
                                    <div className="absolute opacity-0 group-hover:opacity-100 transition-opacity bottom-full mb-2 bg-gray-900 text-white text-xs p-2 rounded-lg whitespace-nowrap z-50 pointer-events-none">
                                        {badge.unlocked ? '🔓 Débloqué !' : `🔒 ${badge.description}`}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Content */}
                {/* MAGIC STORY BANNER (New Feature) */}
                <div className="mb-12 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-3xl p-8 text-white shadow-2xl relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
                    <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-6">
                        <div className="text-center md:text-left">
                            <div className="inline-flex items-center gap-2 bg-white/20 px-3 py-1 rounded-full text-xs font-bold mb-3 uppercase tracking-wider">
                                ✨ Nouveauté
                            </div>
                            <h2 className="text-3xl font-black mb-2 font-chewy">Créez votre propre histoire !</h2>
                            <p className="text-purple-100 max-w-md">Vous avez une idée d'histoire unique pour {childName}? Soumettez-la-nous et notre IA l'écrira et créera les illustrations en quelques secondes.</p>
                        </div>
                        <button
                            onClick={() => {
                                if (profile?.subscription_status === 'active') {
                                    router.push('/dashboard/create');
                                } else {
                                    setClubModalOpen(true);
                                }
                            }}
                            className="bg-white text-purple-600 px-8 py-4 rounded-full font-bold text-lg shadow-lg hover:shadow-xl hover:bg-gray-50 transform hover:-translate-y-1 transition-all flex items-center gap-2"
                        >
                            <span>🪄</span> Créer une histoire magique
                        </button>
                    </div>
                </div>

                {books.length === 0 ? (
                    <div className="bg-white/80 backdrop-blur-sm rounded-[2.5rem] shadow-xl border border-white/50 p-12 text-center max-w-4xl mx-auto mt-10">
                        {/* ... (First story empty state) */}
                        <div className="mb-6 flex justify-center">
                            {/* Magic Book GIF */}
                            <Image
                                src="/images/magic_book_3d.png"
                                width={200}
                                height={200}
                                alt="Livre Magique 3D"
                                className="w-48 h-auto object-contain hover:scale-105 transition-transform"
                            />
                        </div>
                        <h2 className="text-3xl md:text-4xl font-black text-gray-900 mb-4">L'aventure commence ici !</h2>
                        <p className="text-gray-500 max-w-lg mx-auto mb-10 text-lg leading-relaxed">
                            {childName} n'a pas encore son histoire magique.<br />
                            Créez une histoire unique ou personnalisez l'une des histoires de la bibliothèque et voyez ses yeux s'illuminer en se découvrant.
                        </p>
                        {/* Actions Area */}
                        {profile?.subscription_status === 'active' ? (
                            <div className="flex flex-col md:flex-row gap-6 justify-center items-center">
                                {/* Option 1: Magic Create (Purple) */}
                                <Link
                                    href="/dashboard/create"
                                    className="group relative flex items-center justify-center gap-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white w-full md:w-auto px-8 py-4 rounded-full font-bold text-lg hover:shadow-2xl hover:shadow-purple-500/40 transform hover:-translate-y-1 transition-all overflow-hidden"
                                >
                                    <div className="absolute inset-0 bg-white/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700"></div>
                                    <span className="text-2xl">✨</span>
                                    <span>Créer une histoire</span>
                                </Link>

                                {/* Option 2: Library (Orange) */}
                                <Link
                                    href="/books"
                                    className="group flex items-center justify-center gap-3 bg-gradient-to-r from-orange-500 to-orange-600 text-white w-full md:w-auto px-8 py-4 rounded-full font-bold text-lg hover:shadow-2xl hover:shadow-orange-500/40 transform hover:-translate-y-1 transition-all"
                                >
                                    <span className="text-2xl">📖</span>
                                    <span>Choisir une histoire</span>
                                </Link>
                            </div>
                        ) : (
                            <Link href="/books" className="inline-block bg-orange-600 text-white px-10 py-5 rounded-full font-bold text-xl hover:bg-orange-700 transition-all shadow-xl hover:shadow-orange-600/30 transform hover:-translate-y-1">
                                Choisir une histoire dans la bibliothèque 📖
                            </Link>
                        )}
                    </div>
                ) : (
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-8 pb-32">
                        {books.map((book) => (
                            <div key={book.id} className="bg-white rounded-3xl shadow-md border border-gray-100 overflow-hidden hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1 group flex flex-col h-full">
                                {/* Cover Helper */}
                                <div className="aspect-[4/5] bg-orange-50 relative overflow-hidden">
                                    {book.cover_image_url || book.cover_url || (book.story_content?.pages?.[0]?.image) ? (
                                        <Image src={book.cover_image_url || book.cover_url || book.story_content?.pages?.[0]?.image} alt={book.title || "Couverture du livre"} fill className="object-cover transition-transform duration-700 group-hover:scale-105" />
                                    ) : (
                                        <div className="absolute inset-0 flex items-center justify-center text-orange-200">
                                            <span className="text-6xl group-hover:scale-110 transition-transform">📖</span>
                                        </div>
                                    )}

                                    {/* Lock Overlay if Locked (Cannot Read) */}
                                    {!canAccessBook(book) && (
                                        <div className="absolute inset-0 bg-black/60 backdrop-blur-[2px] flex flex-col items-center justify-center text-white p-6 text-center">
                                            <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md mb-4 shadow-lg">
                                                <span className="text-2xl">🔒</span>
                                            </div>
                                            <span className="font-bold text-lg mb-1">Histoire terminée</span>
                                            <span className="text-sm opacity-80">Débloquez pour lire</span>
                                        </div>
                                    )}
                                </div>

                                <div className="p-6 flex flex-col flex-grow">
                                    <h3 className="font-bold text-xl text-gray-900 mb-2 line-clamp-2 leading-tight">
                                        {(book.story_content?.title || book.title || book.title_template || 'l\'Aventure Magique').replace(/\{childName\}|\[Son prénom\]/gi, book.child_name || 'votre enfant')}
                                    </h3>
                                    <p className="text-gray-400 text-xs font-bold uppercase tracking-wider mb-6">
                                        {new Date(book.created_at).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })}
                                    </p>

                                    <div className="mt-auto space-y-3">
                                        <div className="flex gap-3">
                                            <button
                                                onClick={() => handleAction(book, 'read')}
                                                className={`flex-1 py-3 px-4 rounded-xl font-bold border-2 transition-colors flex items-center justify-center gap-2 ${canAccessBook(book)
                                                    ? 'border-orange-500 bg-orange-500 text-white hover:bg-orange-600 hover:border-orange-600 shadow-lg hover:shadow-orange-500/30'
                                                    : 'border-orange-200 text-orange-500 hover:bg-orange-50'
                                                    }`}
                                            >
                                                {canAccessBook(book) ? (
                                                    <><span className="text-lg">📖</span> Lire</>
                                                ) : (
                                                    <><span className="text-lg">🔓</span> Débloquer</>
                                                )}
                                            </button>

                                            {/* Download Button: Handles Unlock via Credit or Pay */}
                                            {/* Download Button: Handles Unlock via Credit or Pay */}
                                            <button
                                                onClick={() => handleAction(book, 'download')}
                                                className={`w-12 h-12 flex items-center justify-center rounded-xl font-bold border-2 transition-colors ${canDownloadBook(book)
                                                    ? 'border-orange-100 text-orange-400 hover:text-orange-600 hover:border-orange-300 hover:bg-orange-50'
                                                    : 'border-gray-100 text-gray-300 hover:border-orange-200 hover:text-orange-400'
                                                    }`}
                                                title={canDownloadBook(book) ? "Télécharger PDF" : "Débloquer le PDF (1 crédit ou Achat)"}
                                            >
                                                {canDownloadBook(book) ? '📥' : '🔒'}
                                            </button>

                                            {/* Share Button (Public Link) */}
                                            <button
                                                onClick={() => {
                                                    // Copy to clipboard logic
                                                    const shareUrl = `${window.location.origin}/share/${book.id}`;
                                                    navigator.clipboard.writeText(shareUrl).then(() => {
                                                        const notification = document.createElement('div');
                                                        notification.className = 'fixed top-24 left-1/2 -translate-x-1/2 z-50 bg-green-500 text-white px-6 py-4 rounded-2xl shadow-xl flex items-center gap-3 animate-in fade-in slide-in-from-top-4';
                                                        notification.innerHTML = '<span class="text-2xl">🔗</span><div class="font-bold">Lien de partage copié !</div>';
                                                        document.body.appendChild(notification);
                                                        setTimeout(() => notification.remove(), 3000);
                                                    });
                                                }}
                                                className="w-12 h-12 flex items-center justify-center rounded-xl font-bold border-2 transition-colors border-purple-100 text-purple-400 hover:text-purple-600 hover:border-purple-300 hover:bg-purple-50"
                                                title="Partager un extrait (Gratuit)"
                                            >
                                                <span>🔗</span>
                                            </button>
                                        </div>

                                        {/* "Commander en papier" - Only if unlocked */}
                                        {canAccessBook(book) && (
                                            <button
                                                className="w-full py-2 px-4 rounded-xl font-bold text-sm bg-gray-50 text-gray-400 border border-gray-100 hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
                                                onClick={() => {
                                                    const notification = document.createElement('div');
                                                    notification.className = 'fixed top-24 left-1/2 -translate-x-1/2 z-50 bg-white border-2 border-orange-500 text-gray-800 px-6 py-4 rounded-2xl shadow-2xl flex items-center gap-3 animate-bounce';
                                                    notification.innerHTML = '<span class="text-2xl">🖨️</span><div><p class="font-bold text-orange-600">Bientôt disponible !</p><p class="text-sm text-gray-600">L\'imprimerie magique se prépare...</p></div>';
                                                    document.body.appendChild(notification);
                                                    setTimeout(() => notification.remove(), 3000);
                                                }}
                                            >
                                                <span>🖨️</span> Commander en papier
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Smart Paywall Modal */}
            <PaymentModal
                isOpen={modalOpen}
                onClose={() => setModalOpen(false)}
                user={user}
                bookId={selectedBookId}
                book={books.find(b => b.id === selectedBookId)}
                profile={profile}
            />

            {/* Club-Only Modal (for Magic Story access) */}
            <ClubModal
                isOpen={clubModalOpen}
                onClose={() => setClubModalOpen(false)}
                user={user}
                childName={childName}
            />

            {/* Credit Confirmation Modal */}
            {creditModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setCreditModalOpen(false)}></div>
                    <div className="relative bg-white rounded-3xl p-8 max-w-sm w-full text-center shadow-2xl animate-in zoom-in-95">
                        <div className="text-5xl mb-4">🎫</div>
                        <h2 className="text-2xl font-black text-gray-900 mb-2">Utiliser 1 Crédit ?</h2>
                        <p className="text-gray-600 mb-8">
                            Il vous reste <strong className="text-orange-600">{profile?.monthly_credits || 0} crédit(s)</strong>.
                            Voulez-vous débloquer le PDF de cette histoire ?
                        </p>
                        <div className="flex flex-col gap-3">
                            <button
                                onClick={() => {
                                    setCreditModalOpen(false);
                                    downloadBook(selectedBookId);
                                    // Update local credit count optimistically
                                    if (profile) {
                                        setProfile({ ...profile, monthly_credits: (profile.monthly_credits || 0) - 1 });
                                    }
                                }}
                                className="w-full bg-orange-600 text-white py-3 rounded-xl font-bold hover:bg-orange-700 transition-colors"
                            >
                                Oui, débloquer (1 Crédit)
                            </button>
                            <button
                                onClick={() => setCreditModalOpen(false)}
                                className="w-full py-3 rounded-xl text-gray-400 font-bold hover:bg-gray-50 transition-colors"
                            >
                                Annuler
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* WELCOME CLUB MODAL */}
            {welcomeModalOpen && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/80 backdrop-blur-sm"></div>
                    <div className="relative bg-white rounded-3xl p-8 max-w-lg w-full text-center shadow-2xl animate-in zoom-in-95 border-4 border-orange-200">
                        <div className="text-6xl mb-4 animate-bounce">🎉</div>
                        <h2 className="text-3xl font-black text-gray-900 mb-2">Bienvenue au Club ! 🌟</h2>
                        <p className="text-gray-600 mb-8 text-lg">
                            Votre abonnement est actif et vous brillez déjà !<br />
                            Vous avez <strong className="text-orange-600">1 crédit disponible</strong>.
                        </p>

                        <div className="bg-orange-50 p-6 rounded-2xl mb-8 border border-orange-100">
                            <p className="font-bold text-gray-800 mb-2">Voulez-vous débloquer votre histoire maintenant ?</p>
                            <p className="text-sm text-gray-500">Cela utilisera 1 crédit pour générer le reste de l'histoire.</p>
                        </div>

                        <button
                            onClick={async () => {
                                try {
                                    const res = await fetch('/api/books/unlock', {
                                        method: 'POST',
                                        headers: { 'Content-Type': 'application/json' },
                                        body: JSON.stringify({ bookId: selectedBookId })
                                    });
                                    if (res.ok) {
                                        // TRIGGER WORKER (Fire and Forget)
                                        fetch('/api/books/process-purchased', {
                                            method: 'POST',
                                            headers: { 'Content-Type': 'application/json' },
                                            body: JSON.stringify({ bookId: selectedBookId })
                                        }).catch(err => console.error("Worker Trigger Error", err));

                                        // Redirect to Reader
                                        router.push(`/read/${selectedBookId}`);
                                    } else {
                                        alert("Erreur lors du déblocage.");
                                    }
                                } catch (e) { console.error(e); }
                            }}
                            className="w-full bg-green-500 text-white py-4 rounded-xl font-bold text-xl hover:bg-green-600 transition-all shadow-lg hover:shadow-green-500/30 flex items-center justify-center gap-2"
                        >
                            <span>🔓</span> Oui, débloquer (Utiliser 1 crédit)
                        </button>
                        <button
                            onClick={() => setWelcomeModalOpen(false)}
                            className="mt-4 text-gray-400 text-sm hover:text-gray-600"
                        >
                            Non, plus tard
                        </button>
                    </div>
                </div>
            )}

            <DashboardBottomNav />
        </div>
    );
}

export default function Dashboard() {
    return (
        <Suspense fallback={<div className="min-h-screen pt-32 text-center">Chargement...</div>}>
            <DashboardContent />
        </Suspense>
    );
}
