'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import PaymentModal from '../components/PaymentModal';

export default function Dashboard() {
    const [user, setUser] = useState(null);
    const [profile, setProfile] = useState(null);
    const [books, setBooks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [modalOpen, setModalOpen] = useState(false);
    const [selectedBookId, setSelectedBookId] = useState(null);

    const router = useRouter();

    useEffect(() => {
        async function fetchDashboardData() {
            try {
                // 1. Get User
                const { data: { session }, error } = await supabase.auth.getSession();
                if (error || !session) {
                    router.push('/login');
                    return;
                }
                setUser(session.user);

                // 2. Get Profile (with Subscription Status)
                const { data: profileData } = await supabase
                    .from('profiles')
                    .select('*')
                    .eq('id', session.user.id)
                    .single();
                setProfile(profileData);

                // 3. Get Books (Generated by User)
                const { data: booksData } = await supabase
                    .from('generated_books')
                    .select('*')
                    .eq('user_id', session.user.id)
                    .order('created_at', { ascending: false });

                setBooks(booksData || []);

            } catch (err) {
                console.error(err);
                // router.push('/login');
            } finally {
                setLoading(false);
            }
        }
        fetchDashboardData();
    }, [router]);

    // Access Logic Checker
    const canAccessBook = (book) => {
        // 1. Club Member?
        if (profile?.subscription_status === 'active') return true;
        // 2. Book Unlocked (One-off purchase)?
        if (book.is_unlocked) return true;

        return false;
    };

    const handleAction = (book, action) => {
        if (canAccessBook(book)) {
            // Authorized
            if (action === 'read') router.push(`/read/${book.id}`);
            if (action === 'download') window.open(`/api/download/${book.id}`, '_blank');
        } else {
            // Unauthorized -> Show Payment Modal
            setSelectedBookId(book.id);
            setModalOpen(true);
        }
    };

    if (loading) return <div className="min-h-screen bg-gray-50 pt-32 flex justify-center"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div></div>;

    return (
        <div className="min-h-screen bg-gray-50 pt-32 pb-20">
            <div className="container mx-auto px-4">

                {/* Header */}
                <div className="flex justify-between items-center mb-10">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">Mon Espace Parents</h1>
                        <p className="text-gray-600">Bienvenue, {profile?.full_name || user?.email}</p>
                        {profile?.subscription_status === 'active' && (
                            <span className="inline-block mt-2 px-3 py-1 bg-gradient-to-r from-orange-400 to-pink-500 text-white rounded-full text-xs font-bold uppercase tracking-wider">
                                Membre Club VIP 🌟
                            </span>
                        )}
                    </div>
                    <Link href="/books" className="bg-orange-500 text-white px-6 py-3 rounded-xl font-bold hover:bg-orange-600 transition-colors shadow-lg hover:shadow-orange-500/30">
                        + Nouvelle Histoire
                    </Link>
                </div>

                {/* Content */}
                {books.length === 0 ? (
                    <div className="bg-white rounded-3xl shadow-sm border border-gray-100 p-12 text-center">
                        <div className="text-6xl mb-6">📚</div>
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">Votre bibliothèque est vide</h2>
                        <p className="text-gray-500 max-w-md mx-auto mb-8">
                            Vous n'avez pas encore personnalisé d'histoires. Créez la première maintenant et voyez les yeux de votre enfant s'illuminer !
                        </p>
                        <Link href="/books" className="text-orange-500 font-bold hover:underline">
                            Découvrir le catalogue →
                        </Link>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {books.map((book) => (
                            <div key={book.id} className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-lg transition-shadow">
                                {/* Cover Helper */}
                                <div className="aspect-[3/4] bg-gray-200 relative">
                                    {/* Ideally we save a cover URL, or use the first image from content */}
                                    {/* Placeholder for now */}
                                    <div className="absolute inset-0 flex items-center justify-center text-gray-400">
                                        <span className="text-4xl">📖</span>
                                    </div>

                                    {/* Lock Overlay if Locked */}
                                    {!canAccessBook(book) && (
                                        <div className="absolute inset-0 bg-black/40 backdrop-blur-[2px] flex flex-col items-center justify-center text-white">
                                            <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md mb-2">
                                                🔒
                                            </div>
                                            <span className="font-bold text-sm">Contenu Verrouillé</span>
                                        </div>
                                    )}
                                </div>

                                <div className="p-6">
                                    <h3 className="font-bold text-xl text-gray-900 mb-1">{book.child_name} et {book.title_template || 'l\'Aventure'}</h3>
                                    <p className="text-gray-500 text-sm mb-6">Crée le {new Date(book.created_at).toLocaleDateString()}</p>

                                    <div className="flex gap-3">
                                        <button
                                            onClick={() => handleAction(book, 'read')}
                                            className={`flex-1 py-3 px-4 rounded-xl font-bold border-2 transition-colors ${canAccessBook(book)
                                                    ? 'border-orange-500 text-orange-600 hover:bg-orange-50'
                                                    : 'border-gray-200 text-gray-400 hover:border-gray-300'
                                                }`}
                                        >
                                            Lire 📖
                                        </button>
                                        <button
                                            onClick={() => handleAction(book, 'download')}
                                            className={`py-3 px-4 rounded-xl font-bold border-2 border-transparent transition-colors ${canAccessBook(book)
                                                    ? 'bg-orange-100 text-orange-700 hover:bg-orange-200'
                                                    : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
                                                }`}
                                            title="Télécharger PDF"
                                        >
                                            📥
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Smart Paywall Modal */}
            <PaymentModal
                isOpen={modalOpen}
                onClose={() => setModalOpen(false)}
                user={user}
                bookId={selectedBookId}
            />
        </div>
    );
}
